name: Main workflows
on:
  push:
    branches:
      - main

jobs:
  benchmark:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Upload docs and run benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
      - name: Cache cargo
        uses: actions/cache@v3
        with:
          path: |
            target
            !target/doc_upload
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-cargo-doc-bench-${{ hashFiles('**/Cargo.lock') }}
      - name: Generate documentation
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: -v --document-private-items --all-features
      - run: echo "<meta http-equiv=refresh content=0;url=vsop87/index.html>" > target/doc/index.html
      - run: |
          if [ -d target/doc_upload ]; then rm -rf target/doc_upload; fi
          mkdir target/doc_upload && mv target/doc target/doc_upload/doc
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: target/doc_upload
